fftTest:fftTest.c
	g++ -Wall -Wno-unused-function fftTest.c ../lodepng/lodepng.cpp -lm -o fftTest
saveTest:saveTest.c
	g++ -Wall -Wno-unused-function saveTest.c ../lodepng/lodepng.cpp -lm -o saveTest
clear:
	rm fftTest saveTest
