fftRings2:fftRings2.cpp
	g++ -Wall -Wno-unused-function fftRings2.cpp ../fft/fft.c ../lodepng/lodepng.cpp -lm -o fftRings2
fftRings:fftRings.cpp
	g++ -Wall -Wno-unused-function fftRings.cpp ../fft/fft.c ../lodepng/lodepng.cpp -lm -o fftRings
fftTestImage:fftTestImage.c
	g++ -Wall -Wno-unused-function fftTestImage.c ../fft/fft.c ../lodepng/lodepng.cpp -lm -o fftTestImage
saveTest:saveTest.c
	g++ -Wall -Wno-unused-function saveTest.c ../lodepng/lodepng.cpp -lm -o saveTest
clean:
	rm fftTestImage saveTest fftRings fftRings2
